apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: test-deploy
  namespace: supply
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: test-deploy
    spec:
      initContainers:
        - name: busybox
          image: alpine/git
          env:
            - name: GS_TOKEN
              value: XXXXXXXX
          args:
            - clone
            - --single-branch
            - --
            - git clone https://oauth2:${GS_TOKEN}@magic.pathao.com/fellowship/loadmaster.git
            - /etc/root 
          volumeMounts:
            - name: test-volume
              mountPath: /etc/root
      containers:
      - name: hello-busybox
        image: ubuntu
        command:
          - "/bin/bash"
          - "-c"
        args:
        - "while true; do echo hello; sleep 10; done;"
        volumeMounts:
          - name: test-volume
            mountPath: /etc/root
      volumes:
        - name: test-volume
          emptyDir: {}
            
          